# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reservation.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'reservation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11reservation.proto\"W\n\x12ReservationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x18\n\x10reservation_type\x18\x02 \x01(\t\x12\x16\n\x0ereservation_id\x18\x03 \x01(\t\"\'\n\rCancelRequest\x12\x16\n\x0ereservation_id\x18\x01 \x01(\x05\"1\n\x13ReservationResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t2\x8f\x01\n\x12ReservationService\x12>\n\x11\x43reateReservation\x12\x13.ReservationRequest\x1a\x14.ReservationResponse\x12\x39\n\x11\x43\x61ncelReservation\x12\x0e.CancelRequest\x1a\x14.ReservationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reservation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESERVATIONREQUEST']._serialized_start=21
  _globals['_RESERVATIONREQUEST']._serialized_end=108
  _globals['_CANCELREQUEST']._serialized_start=110
  _globals['_CANCELREQUEST']._serialized_end=149
  _globals['_RESERVATIONRESPONSE']._serialized_start=151
  _globals['_RESERVATIONRESPONSE']._serialized_end=200
  _globals['_RESERVATIONSERVICE']._serialized_start=203
  _globals['_RESERVATIONSERVICE']._serialized_end=346
# @@protoc_insertion_point(module_scope)
