# Generated by Django 5.1.5 on 2025-02-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('reservation_type', models.CharField(choices=[('HOTEL', 'Hotel'), ('TRAIN', 'Train'), ('FLIGHT', 'Flight')], max_length=10)),
                ('reservation_id', models.CharField(max_length=100)),
                ('status', models.CharField(default='PENDING', max_length=20)),
            ],
        ),
    ]
